//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABILITY_CATALOG
    {
        public ABILITY_CATALOG()
        {
            this.GAME_ABILITY = new HashSet<GAME_ABILITY>();
            this.GAME_USER_ABILITY = new HashSet<GAME_USER_ABILITY>();
        }
    
        public int abilityID { get; set; }
        public Nullable<int> adminID { get; set; }
        public string name { get; set; }
        public int versionAbility { get; set; }
        public int points { get; set; }
        public int ranking { get; set; }
        public int experience { get; set; }
        public int wins { get; set; }
        public int defeats { get; set; }
    
        public virtual ICollection<GAME_ABILITY> GAME_ABILITY { get; set; }
        public virtual ICollection<GAME_USER_ABILITY> GAME_USER_ABILITY { get; set; }
        public virtual ADMIN_USER ADMIN_USER { get; set; }
    }
}
