//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_USER
    {
        public ADMIN_USER()
        {
            this.ABILITY_CATALOG = new HashSet<ABILITY_CATALOG>();
            this.SHIP_CATALOG = new HashSet<SHIP_CATALOG>();
        }
    
        public int userID { get; set; }
        public int nickAndPassID { get; set; }
        public string name { get; set; }
        public string secondName { get; set; }
        public string email { get; set; }
        public System.DateTime regDate { get; set; }
    
        public virtual ICollection<ABILITY_CATALOG> ABILITY_CATALOG { get; set; }
        public virtual ICollection<SHIP_CATALOG> SHIP_CATALOG { get; set; }
        public virtual USER_NICK_PASS USER_NICK_PASS { get; set; }
    }
}
