//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOARD_BOX
    {
        public BOARD_BOX()
        {
            this.BOARD_SHIP = new HashSet<BOARD_SHIP>();
        }
    
        public int playerID { get; set; }
        public int posX { get; set; }
        public int posY { get; set; }
        public bool alive { get; set; }
    
        public virtual GAME_PLAYER GAME_PLAYER { get; set; }
        public virtual ICollection<BOARD_SHIP> BOARD_SHIP { get; set; }
    }
}
