//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_PLAYER
    {
        public GAME_PLAYER()
        {
            this.BOARD_BOX = new HashSet<BOARD_BOX>();
            this.CHAT_MESSAGE = new HashSet<CHAT_MESSAGE>();
            this.GAME_ABILITY = new HashSet<GAME_ABILITY>();
            this.GAME_AND_PLAYER = new HashSet<GAME_AND_PLAYER>();
            this.SHOT_FEED = new HashSet<SHOT_FEED>();
            this.GAME_SHIP = new HashSet<GAME_SHIP>();
        }
    
        public int playerID { get; set; }
        public Nullable<int> gameUserID { get; set; }
        public System.DateTime lastFeed { get; set; }
        public int availableShots { get; set; }
        public int remainingShips { get; set; }
        public bool winFeedDelivered { get; set; }
        public bool inTurn { get; set; }
        public int hitShots { get; set; }
        public int missShots { get; set; }
        public int points { get; set; }
        public bool @lock { get; set; }
    
        public virtual ICollection<BOARD_BOX> BOARD_BOX { get; set; }
        public virtual ICollection<CHAT_MESSAGE> CHAT_MESSAGE { get; set; }
        public virtual ICollection<GAME_ABILITY> GAME_ABILITY { get; set; }
        public virtual ICollection<GAME_AND_PLAYER> GAME_AND_PLAYER { get; set; }
        public virtual ICollection<SHOT_FEED> SHOT_FEED { get; set; }
        public virtual GAME_USER GAME_USER { get; set; }
        public virtual ICollection<GAME_SHIP> GAME_SHIP { get; set; }
    }
}
