//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_ABILITY
    {
        public GAME_ABILITY()
        {
            this.SHIELD = new HashSet<SHIELD>();
        }
    
        public int playerID { get; set; }
        public int abilityID { get; set; }
        public bool active { get; set; }
        public int availableCount { get; set; }
    
        public virtual ABILITY_CATALOG ABILITY_CATALOG { get; set; }
        public virtual ONE_PLUS_ABILITY ONE_PLUS_ABILITY { get; set; }
        public virtual GAME_PLAYER GAME_PLAYER { get; set; }
        public virtual ICollection<SHIELD> SHIELD { get; set; }
    }
}
