//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVE_TERMINAL
    {
        public LIVE_TERMINAL()
        {
            this.LIVE_GAME = new HashSet<LIVE_GAME>();
        }
    
        public int idTerminal { get; set; }
        public string keyTerminal { get; set; }
    
        public virtual ICollection<LIVE_GAME> LIVE_GAME { get; set; }
    }
}
