//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBP_Data_Entities : DbContext
    {
        public MBP_Data_Entities()
            : base("name=MBP_Data_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABILITY_CATALOG> ABILITY_CATALOG { get; set; }
        public virtual DbSet<ADMIN_USER> ADMIN_USER { get; set; }
        public virtual DbSet<BOARD_BOX> BOARD_BOX { get; set; }
        public virtual DbSet<BOARD_SHIP> BOARD_SHIP { get; set; }
        public virtual DbSet<CHAT_MESSAGE> CHAT_MESSAGE { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<GAME> GAME { get; set; }
        public virtual DbSet<GAME_ABILITY> GAME_ABILITY { get; set; }
        public virtual DbSet<GAME_AND_PLAYER> GAME_AND_PLAYER { get; set; }
        public virtual DbSet<GAME_PLAYER> GAME_PLAYER { get; set; }
        public virtual DbSet<GAME_SHIP> GAME_SHIP { get; set; }
        public virtual DbSet<GAME_SHIP_CATALOG> GAME_SHIP_CATALOG { get; set; }
        public virtual DbSet<GAME_USER> GAME_USER { get; set; }
        public virtual DbSet<GAME_USER_ABILITY> GAME_USER_ABILITY { get; set; }
        public virtual DbSet<LIVE_GAME> LIVE_GAME { get; set; }
        public virtual DbSet<LIVE_TERMINAL> LIVE_TERMINAL { get; set; }
        public virtual DbSet<MOD_USER> MOD_USER { get; set; }
        public virtual DbSet<ONE_PLUS_ABILITY> ONE_PLUS_ABILITY { get; set; }
        public virtual DbSet<PLAYED_GAME> PLAYED_GAME { get; set; }
        public virtual DbSet<SHIELD> SHIELD { get; set; }
        public virtual DbSet<SHIP_CATALOG> SHIP_CATALOG { get; set; }
        public virtual DbSet<SHOT_FEED> SHOT_FEED { get; set; }
        public virtual DbSet<SYSTEM_MESSAGE> SYSTEM_MESSAGE { get; set; }
        public virtual DbSet<USER_NICK_PASS> USER_NICK_PASS { get; set; }
        public virtual DbSet<USER_PHOTO> USER_PHOTO { get; set; }
        public virtual DbSet<VW_ADMIN_USER_EXT> VW_ADMIN_USER_EXT { get; set; }
        public virtual DbSet<VW_BOARD_BOX_EXT> VW_BOARD_BOX_EXT { get; set; }
        public virtual DbSet<VW_CHAT_MESSAGE_EXT> VW_CHAT_MESSAGE_EXT { get; set; }
        public virtual DbSet<VW_GAME_ABILITY_EXT> VW_GAME_ABILITY_EXT { get; set; }
        public virtual DbSet<VW_GAME_AND_PLAYER_INFO> VW_GAME_AND_PLAYER_INFO { get; set; }
        public virtual DbSet<VW_GAME_PLAYER_EXT> VW_GAME_PLAYER_EXT { get; set; }
        public virtual DbSet<VW_GAME_SHIP_CATALOG> VW_GAME_SHIP_CATALOG { get; set; }
        public virtual DbSet<VW_GAME_SHIP_EXT> VW_GAME_SHIP_EXT { get; set; }
        public virtual DbSet<VW_GAME_USER_ABILITY_EXT> VW_GAME_USER_ABILITY_EXT { get; set; }
        public virtual DbSet<VW_GAME_USER_EXT> VW_GAME_USER_EXT { get; set; }
        public virtual DbSet<VW_LIVE_GAME> VW_LIVE_GAME { get; set; }
        public virtual DbSet<VW_MOD_USER_EXT> VW_MOD_USER_EXT { get; set; }
        public virtual DbSet<VW_PLAYED_GAME_EXT> VW_PLAYED_GAME_EXT { get; set; }
        public virtual DbSet<VW_SHOT_FEED_EXT> VW_SHOT_FEED_EXT { get; set; }
    }
}
