//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBP_LIVE_SHIPS
    {
        public int liveShipsID { get; set; }
        public int gameShipID { get; set; }
        public int indexShip { get; set; }
        public int gameID { get; set; }
        public int playerID { get; set; }
    
        public virtual GAME GAME { get; set; }
        public virtual GAME_SHIP GAME_SHIP { get; set; }
    }
}
