//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIP_CATALOG
    {
        public SHIP_CATALOG()
        {
            this.GAME_SHIP = new HashSet<GAME_SHIP>();
            this.GAME_SHIP_CATALOG = new HashSet<GAME_SHIP_CATALOG>();
        }
    
        public System.Guid uniqueID { get; set; }
        public int shipID { get; set; }
        public Nullable<int> adminID { get; set; }
        public Nullable<int> shipVersion { get; set; }
        public string name { get; set; }
        public int points { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string photo { get; set; }
        public bool active { get; set; }
    
        public virtual ADMIN_USER ADMIN_USER { get; set; }
        public virtual ICollection<GAME_SHIP> GAME_SHIP { get; set; }
        public virtual ICollection<GAME_SHIP_CATALOG> GAME_SHIP_CATALOG { get; set; }
    }
}
