//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GAME_USER_EXT
    {
        public int userID { get; set; }
        public int nickAndPassID { get; set; }
        public string name { get; set; }
        public string secondName { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string genre { get; set; }
        public System.DateTime regDate { get; set; }
        public int wins { get; set; }
        public int defeats { get; set; }
        public int hits { get; set; }
        public int misses { get; set; }
        public int totalPoints { get; set; }
        public int points { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string personalDescription { get; set; }
        public string nickname { get; set; }
    }
}
