//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GAME_SHIP_CATALOG
    {
        public int gameID { get; set; }
        public int shipCount { get; set; }
        public int shipID { get; set; }
        public int shipVersion { get; set; }
        public string name { get; set; }
        public int points { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string photo { get; set; }
    }
}
