//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GAME_PLAYER_EXT
    {
        public int playerID { get; set; }
        public Nullable<int> gameUserID { get; set; }
        public System.DateTime lastFeed { get; set; }
        public int availableShots { get; set; }
        public int remainingShips { get; set; }
        public bool winFeedDelivered { get; set; }
        public bool inTurn { get; set; }
        public int hitShots { get; set; }
        public int missShots { get; set; }
        public int points { get; set; }
        public bool @lock { get; set; }
        public string nickname { get; set; }
    }
}
