//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GAME_SHIP_EXT
    {
        public int gameShipID { get; set; }
        public int shipID { get; set; }
        public int playerID { get; set; }
        public int integrity { get; set; }
        public int posX { get; set; }
        public int posY { get; set; }
        public string nickname { get; set; }
    }
}
