//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GAME_ABILITY_EXT
    {
        public string nickname { get; set; }
        public int playerID { get; set; }
        public int abilityID { get; set; }
        public bool active { get; set; }
        public int availableCount { get; set; }
        public string direction { get; set; }
    }
}
