//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LIVE_GAME
    {
        public int idLiveGame { get; set; }
        public int modID { get; set; }
        public int gameID { get; set; }
        public int idTerminal { get; set; }
        public string nickname { get; set; }
    }
}
