//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBP_DataAccess.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SHOT_FEED_EXT
    {
        public int shotFeedID { get; set; }
        public int againstPlayerID { get; set; }
        public int posX { get; set; }
        public int posY { get; set; }
        public bool success { get; set; }
        public bool bomb { get; set; }
        public string nickname { get; set; }
        public bool destroyedShield { get; set; }
    }
}
